### ISSUE TITLE
 功能大众，很好用

### ISSUE THREAD

**Issue by zfx1101804091** [binzh303/simple-fast-generator#1]
is:issue is:open 功能大众，很好用，如果全库生成代码，可以 注释掉sc.setInclude("tb_brand","tb_category","tb_category_brand");
`//        sc.setInclude("tb_brand","tb_category","tb_category_brand"); // 表名，用，隔开  需要生产`

**Comment by binzh303** [comment]
感谢支持！如果只是有少数几个表不想生成，可以把 // sc.setInclude("");注释掉，
用 sc.setExclude(""); // 不需要生成的表  二选一，
多个表的话同样用 , 隔开即可。
